version: '3.8'

services:
  postgres: 
    image: postgres:14
    container_name: timetable-db
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    entrypoint: 
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
